# Generated by Django 5.2.7 on 2025-10-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='liked_games', to='MyWebsite.user'),
        ),
    ]
