# Generated by Django 5.2.7 on 2025-10-15 11:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='BooksApp.registration')),
                ('users_who_like', models.ManyToManyField(related_name='liked_books', to='BooksApp.registration')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='books_uploaded',
            field=models.ManyToManyField(related_name='uploaded_users', to='BooksApp.book'),
        ),
        migrations.AddField(
            model_name='registration',
            name='like_books',
            field=models.ManyToManyField(related_name='liked_users', to='BooksApp.book'),
        ),
    ]
