# Generated by Django 5.2.7 on 2025-10-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=100),
        ),
    ]
